### ISSUE TITLE
"NOT SUPPORTED IN THIS VERSION" error

### ISSUE THREAD

**Issue by nicost** [ClearVolume/ClearGL#12]
After updating cleargl from 1.0.7 to 2.0.4, I get the following uncaught exception when rendering volumes with more than 1 plane:

java.lang.NullPointerException
	at cleargl.GLTexture.<init>(GLTexture.java:104)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.ensureTextureAllocated(ClearGLVolumeRenderer.java:631)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.displayInternal(ClearGLVolumeRenderer.java:509)
	at clearvolume.renderer.cleargl.ClearGLVolumeRenderer.display(ClearGLVolumeRenderer.java:491)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
etc...
NOT SUPPORTED IN THIS VERSION

A search for "NOT SUPPORTED IN THIS VERSION GetGl4" leads to: http://forum.jogamp.org/OpenGL-4-status-td2969055.html, which suggests that my graphics card (Intel Iris 1536MB on Mac Mini Late 2014, OS X 10.11.6) does not support OpenGl4.  Interestingly, this page (https://support.apple.com/en-us/HT202823) suggests that my card should support OpenGl 4.1, so the root cause may be something different.  Shouldn't the openGl version that the card supports be checked somewhere?
Any idea when this was introduced, so that I can go back to the last working version?

**Comment by skalarproduktraum** [comment]
Hey Nico! I have to look into this, as you state, OpenGL 4.1 should and is supported by the 2014 Mac Mini/Iris Graphics. The version of OpenGL your GPU supports is actually checked during window creation and you should get an error if the machine does not support the requested version, which in our case it 4.1 or higher.

We decided to drop support for OpenGL 3.3 for the reason that the graphics cards that are not able to support OpenGL 4.1 usually don't have enough memory or computational power to run ClearVolume nicely (this applies e.g. to the 2011 MacBook Air).

**Comment by skalarproduktraum** [comment]
Addition: Could you please check the output in the console window or stdout for a line like
```
ClearGLWindow: GLProfile[GL4bc/GL4bc.hw]
```

This would indicate you are actually getting an OpenGL 4 context. There was a very weird OS X bug some time ago that caused getting back a differently-versioned OpenGL context than you requested. I just want to exclude that's the case. Thanks!

**Comment by skalarproduktraum** [comment]
And just to confirm, do I understand you correctly -- single-plane images work?

**Comment by nicost** [comment]
The output does show the line:

> ClearGLWindow: GLProfile[GL4/GL4.hw]

and indeed, single-place images work (even multi-channel), volumes do not.  The older versions (CoreMem 0.1.5, clearvolume 1.1.4, cleargl 1.0.7) work fine.  Happy to try to find the version where it breaks, but the problem is that changing one of the versions of these libraries invariably leads to some kind of weird error, and the poms have no guidance which versions work with what.

**Comment by nicost** [comment]
Just noted that mine says "GL4", i.e. not "GL4bc".  Is that the problem?

**Comment by nicost** [comment]
Is there any progress on this?  Anything you want me to try?  I would like to change the way video capture works (have the library return images rather than write itself to disk), and it does not seem to make much sense to do that in an old version (unless you think those PRs can easily be ported).

**Comment by skalarproduktraum** [comment]
Hey Nico,

apologies for the silence! I just had a look into the issue again and am quite puzzled. Whether you get a GL4 or a GL4bc doesn't matter for us at the moment, both should work. I really don't understand why getGL4() throws this error. I'll try to find a similar machine, so I can find the root cause, however I'll most probably not get to that before next week. 

If you want to add the functionality for getting a series of images in 1.0.7, that should not be a problem to port later, as that part of the code has not changed much. We merely bumped to 2.x because we removed some legacy classes, and introduced some breaking API changes.

**Comment by nicost** [comment]
Looking at this again, I realized that the "NOT SUPPORTED IN THIS VERSION" originates from clearvolume.renderer.opencl.fillWithByteBuffer(), and is the same problem as issue #62 (https://github.com/ClearVolume/ClearVolume/issues/62).  It would be really useful to annotate exceptions like these with their source, as it is close to impossible to follow the path to its origin and realize what the actual exception is.
